I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: "D:\\Ren'Py Project\\unregelmaessige verben\\game\\saves\\navigation.json.new" -> "D:\\Ren'Py Project\\unregelmaessige verben\\game\\saves\\navigation.json"

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Ren'Py\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "D:\Ren'Py\renpy\main.py", line 599, in main
    renpy.dump.dump(False)
  File "D:\Ren'Py\renpy\dump.py", line 262, in dump
    os.rename(new, filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: "D:\\Ren'Py Project\\unregelmaessige verben\\game\\saves\\navigation.json.new" -> "D:\\Ren'Py Project\\unregelmaessige verben\\game\\saves\\navigation.json"

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.4.24120703
unregelmaessige verben 1.0
Fri Dec 20 11:49:58 2024
